# Generated by Django 2.2.10 on 2020-02-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
