# Generated by Django 2.2.10 on 2020-02-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_queue', '0002_auto_20200212_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
