# Generated by Django 2.2.10 on 2020-02-13 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_queue', '0003_auto_20200212_0529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
